question_data = [
  {"question":"The HTML5 standard was published in 2014.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"The common software-programming acronym &quot;I18N&quot; comes from the term &quot;Interlocalization&quot;.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"The first computer bug was formed by faulty wires.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"FLAC stands for &quot;Free Lossless Audio Condenser&quot;&#039;","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"The very first recorded computer &quot;bug&quot; was a moth found inside a Harvard Mark II computer.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"All program codes have to be compiled into an executable file in order to be run. This file can then be executed on any machine.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"Linus Torvalds created Linux and Git.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"The logo for Snapchat is a Bell.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"&quot;Windows NT&quot; is a monolithic kernel.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"RAM stands for Random Access Memory.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"The open source program Redis is a relational database server.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"DHCP stands for Dynamic Host Configuration Port.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"&quot;HTML&quot; stands for Hypertext Markup Language.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"In most programming languages, the operator ++ is equivalent to the statement &quot;+= 1&quot;.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"Early RAM was directly seated onto the motherboard and could not be easily removed.","correct_answer":"True","incorrect_answers":["False"]},
  {"difficulty":"easy","question":"The Windows 7 operating system has six main editions.","correct_answer":"True","incorrect_answers":["False"]},
  {"difficulty":"easy","question":"The Windows ME operating system was released in the year 2000.","correct_answer":"True","incorrect_answers":["False"]},
  {"difficulty":"easy","question":"The NVidia GTX 1080 gets its name because it can only render at a 1920x1080 screen resolution.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"The first dual-core CPU was the Intel Pentium D.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"The last Windows operating system to be based on the Windows 9x kernel was Windows 98.","correct_answer":"False","incorrect_answers":["True"]},
  {"difficulty":"easy","question":"Linux was first created as an alternative to Windows XP.","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"Android versions are named in alphabetical order.","correct_answer":"True","incorrect_answers":["False"]},
  {"question":"A Boolean value of &quot;0&quot; represents which of these words?","correct_answer":"False","incorrect_answers":["True"]},
  {"question":"The Python programming language gets its name from the British comedy group 'Monty Python'.","correct_answer":"True","incorrect_answers":["False"]}
]